[workspace]
members = [
  "compiler/rust/crates/squidvm-limits",
  "compiler/rust/crates/squidc-core",
  "compiler/rust/crates/squid-device-protocol",
  "compiler/rust/crates/squidvm-core",
  "compiler/rust/crates/squidvm-ffi",
  "compiler/rust/crates/squidc-cli",
  "compiler/rust/crates/squidc-wasm",
  "firmware/native/crates/squidscript-fw-core",
  "firmware/native/crates/squidscript-fw-x4"
]
resolver = "2"

[profile.dev]
opt-level = 2

[patch.crates-io]
esp-radio = { path = "firmware/native/patches/esp-radio" }
