from pathlib import Path
import json
import os
import re
import subprocess
import sys
import tempfile

from scripts.tests.zephyr_test_utils import ROOT, ZephyrScriptTestCase


class ZephyrFfiAbiTests(ZephyrScriptTestCase):
    def test_squidvm_ffi_abi_checker_validates_current_manifest(self):
        checker = ROOT / "scripts/check-squidvm-ffi-abi.py"
        manifest_path = ROOT / "compiler/rust/crates/squidvm-ffi/abi/manifest.json"
        coverage_doc = self.read("docs/zephyr_vm_host_abi_coverage.md")

        result = subprocess.run(
            [sys.executable, str(checker), "--check"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )

        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        export_names = {item["name"] for item in manifest["exports"]}
        callback_fields = {item["field"] for item in manifest["callbacks"]}

        self.assertIn("sqvm_dispatch_start_resumable_with_payload", export_names)
        self.assertIn("sqvm_trigger_ble_profile_read", export_names)
        self.assertIn("sqdp_parse_event_dispatch_request", export_names)
        self.assertIn("sqdc_plan_device_binding", export_names)
        self.assertIn("wifi_scan_network", callback_fields)
        self.assertIn("system_memory_text", callback_fields)
        self.assertIn("power_sleep", callback_fields)
        self.assertIn("<!-- BEGIN SQUIDVM_FFI_ABI_MANIFEST -->", coverage_doc)
        self.assertIn("<!-- END SQUIDVM_FFI_ABI_MANIFEST -->", coverage_doc)
        self.assertIn("Generated by scripts/check-squidvm-ffi-abi.py --write-header", self.read("firmware/zephyr/src/squidvm_ffi.h"))

    def test_squidvm_ffi_abi_checker_generates_header_from_manifest(self):
        checker = ROOT / "scripts/check-squidvm-ffi-abi.py"

        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            rust = tmp_path / "lib.rs"
            header = tmp_path / "squidvm_ffi.h"
            runtime = tmp_path / "vm_runtime.c"
            rust_tests = tmp_path / "ffi_dispatch.rs"
            generated_callbacks = tmp_path / "generated_callbacks.rs"
            generated_result_defaults = tmp_path / "generated_result_defaults.rs"
            generated_dispatch_cases = tmp_path / "generated_ffi_dispatch_cases.rs"
            generated_runtime_callbacks = tmp_path / "generated_runtime_callbacks.inc"
            zephyr_tests = tmp_path / "main.c"
            manifest = tmp_path / "manifest.json"
            doc = tmp_path / "coverage.md"

            rust.write_text(
                """
#[repr(C)]
pub struct SqvmCallbacks {
    pub trace: Option<unsafe extern "C" fn()>,
}

#[no_mangle]
pub extern "C" fn sqvm_present() {}
""",
                encoding="utf-8",
            )
            runtime.write_text(
                """
static const SqvmCallbacks runtime_callbacks = {
#include "generated_runtime_callbacks.inc"
};
""",
                encoding="utf-8",
            )
            rust_tests.write_text("fn covers_trace() {}\n", encoding="utf-8")
            zephyr_tests.write_text(
                "ZTEST(squidscript_protocol, test_trace_boundary)\n",
                encoding="utf-8",
            )
            doc.write_text("# Coverage\n", encoding="utf-8")
            manifest.write_text(
                json.dumps(
                    {
                        "format": "squidscript-squidvm-ffi-abi-v1",
                        "header": {
                            "guard": "SQUIDSCRIPT_TEST_FFI_H",
                            "includes": ["stddef.h", "stdint.h"],
                        },
                        "constants": [
                            {
                                "name": "SQVM_TEST_CAP",
                                "definition": "#define SQVM_TEST_CAP 4",
                            }
                        ],
                        "types": [
                            {
                                "name": "SqvmStatus",
                                "definition": "typedef enum {\n\tSQVM_STATUS_OK = 0,\n} SqvmStatus;",
                            },
                            {
                                "name": "SqvmTraceCallback",
                                "definition": "typedef void (*SqvmTraceCallback)(void *user_data);",
                            },
                            {
                                "name": "SqvmCallbacks",
                                "definition": "typedef struct {\n\tSqvmTraceCallback trace;\n} SqvmCallbacks;",
                            },
                        ],
                        "result_defaults": [
                            {
                                "type": "SqvmTestResult",
                                "rust_fields": [
                                    {"field": "ok", "value": "false"},
                                    {"field": "error", "literal": "unsupported"},
                                    {"field": "path", "null": True},
                                ],
                                "c_helpers": [
                                    {
                                        "name": "sqvm_test_result_unsupported",
                                        "fields": [
                                            {"field": "ok", "value": "false"},
                                            {"field": "error", "literal": "unsupported"},
                                            {"field": "path", "null": True},
                                        ],
                                    }
                                ],
                            }
                        ],
                        "exports": [
                            {
                                "name": "sqvm_present",
                                "family": "vm",
                                "direction": "rust_to_c",
                                "prototype": "void sqvm_present(void);",
                            }
                        ],
                        "callbacks": [
                            {
                                "field": "trace",
                                "typedef": "SqvmTraceCallback",
                                "family": "core",
                                "rust_type": "Option<unsafe extern \"C\" fn(user_data: *mut c_void)>",
                                "missing_policy": "noop",
                                "test_fixture": "compile_trace_sqbc",
                                "failing_callback": "failing_trace",
                            }
                        ],
                        "coverage": [
                            {
                                "family": "Core",
                                "callbacks": ["trace"],
                                "rust": "fake rust coverage",
                                "zephyr": "fake zephyr coverage",
                                "rust_tests": ["covers_trace"],
                                "zephyr_tests": ["test_trace_boundary"],
                            }
                        ],
                    },
                    indent=2,
                ),
                encoding="utf-8",
            )

            emit_result = subprocess.run(
                [
                    sys.executable,
                    str(checker),
                    "--emit-header",
                    "--manifest",
                    str(manifest),
                    "--rust",
                    str(rust),
                    "--header",
                    str(header),
                    "--runtime",
                    str(runtime),
                    "--rust-tests",
                    str(rust_tests),
                    "--generated-rust-callbacks",
                    str(generated_callbacks),
                    "--generated-rust-result-defaults",
                    str(generated_result_defaults),
                    "--generated-rust-dispatch-cases",
                    str(generated_dispatch_cases),
                    "--generated-runtime-callbacks",
                    str(generated_runtime_callbacks),
                    "--zephyr-tests",
                    str(zephyr_tests),
                    "--coverage-doc",
                    str(doc),
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
            )

            self.assertEqual(emit_result.returncode, 0, emit_result.stderr + emit_result.stdout)
            self.assertIn("#ifndef SQUIDSCRIPT_TEST_FFI_H", emit_result.stdout)
            self.assertIn("#define SQVM_TEST_CAP 4", emit_result.stdout)
            self.assertIn("void sqvm_present(void);", emit_result.stdout)

            write_result = subprocess.run(
                [
                    sys.executable,
                    str(checker),
                    "--write-header",
                    "--write-doc",
                    "--write-generated",
                    "--manifest",
                    str(manifest),
                    "--rust",
                    str(rust),
                    "--header",
                    str(header),
                    "--runtime",
                    str(runtime),
                    "--rust-tests",
                    str(rust_tests),
                    "--generated-rust-callbacks",
                    str(generated_callbacks),
                    "--generated-rust-result-defaults",
                    str(generated_result_defaults),
                    "--generated-rust-dispatch-cases",
                    str(generated_dispatch_cases),
                    "--generated-runtime-callbacks",
                    str(generated_runtime_callbacks),
                    "--zephyr-tests",
                    str(zephyr_tests),
                    "--coverage-doc",
                    str(doc),
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
            )

            self.assertEqual(write_result.returncode, 0, write_result.stderr + write_result.stdout)
            self.assertIn(
                "impl Default for SqvmTestResult",
                generated_result_defaults.read_text(encoding="utf-8"),
            )
            self.assertIn(
                'error: b"unsupported".as_ptr()',
                generated_result_defaults.read_text(encoding="utf-8"),
            )
            self.assertIn(
                "static inline void sqvm_test_result_unsupported(SqvmTestResult *out)",
                header.read_text(encoding="utf-8"),
            )
            self.assertIn(
                "out->error_len = sizeof(\"unsupported\") - 1;",
                header.read_text(encoding="utf-8"),
            )
            header.write_text(header.read_text(encoding="utf-8") + "\n/* hand edit */\n", encoding="utf-8")
            generated_callbacks.write_text(generated_callbacks.read_text(encoding="utf-8") + "\n// hand edit\n", encoding="utf-8")
            generated_result_defaults.write_text(generated_result_defaults.read_text(encoding="utf-8") + "\n// hand edit\n", encoding="utf-8")
            generated_dispatch_cases.write_text(generated_dispatch_cases.read_text(encoding="utf-8") + "\n// hand edit\n", encoding="utf-8")
            generated_runtime_callbacks.write_text(generated_runtime_callbacks.read_text(encoding="utf-8") + "\n/* hand edit */\n", encoding="utf-8")

            check_result = subprocess.run(
                [
                    sys.executable,
                    str(checker),
                    "--check",
                    "--manifest",
                    str(manifest),
                    "--rust",
                    str(rust),
                    "--header",
                    str(header),
                    "--runtime",
                    str(runtime),
                    "--rust-tests",
                    str(rust_tests),
                    "--generated-rust-callbacks",
                    str(generated_callbacks),
                    "--generated-rust-result-defaults",
                    str(generated_result_defaults),
                    "--generated-rust-dispatch-cases",
                    str(generated_dispatch_cases),
                    "--generated-runtime-callbacks",
                    str(generated_runtime_callbacks),
                    "--zephyr-tests",
                    str(zephyr_tests),
                    "--coverage-doc",
                    str(doc),
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
            )

        self.assertNotEqual(check_result.returncode, 0)
        combined = check_result.stderr + check_result.stdout
        self.assertIn("generated C header is stale", combined)
        self.assertIn("generated Rust callback module is stale", combined)
        self.assertIn("generated Rust result defaults module is stale", combined)
        self.assertIn("generated Rust dispatch cases are stale", combined)
        self.assertIn("generated Zephyr runtime callback initializer is stale", combined)

    def test_squidvm_ffi_abi_checker_reports_symbol_drift(self):
        checker = ROOT / "scripts/check-squidvm-ffi-abi.py"

        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            rust = tmp_path / "lib.rs"
            header = tmp_path / "squidvm_ffi.h"
            runtime = tmp_path / "vm_runtime.c"
            rust_tests = tmp_path / "ffi_dispatch.rs"
            zephyr_tests = tmp_path / "main.c"
            manifest = tmp_path / "manifest.json"
            doc = tmp_path / "coverage.md"

            rust.write_text(
                """
#[repr(C)]
pub struct SqvmCallbacks {
    pub trace: Option<unsafe extern "C" fn()>,
}

#[no_mangle]
pub extern "C" fn sqvm_present(void) {}

#[no_mangle]
pub extern "C" fn sqvm_unlisted_rust(void) {}
""",
                encoding="utf-8",
            )
            header.write_text(
                """
typedef struct {
    SqvmTraceCallback trace;
} SqvmCallbacks;

void sqvm_present(void);
void sqvm_unlisted_header(void);
""",
                encoding="utf-8",
            )
            runtime.write_text(
                """
static const SqvmCallbacks runtime_callbacks = {
    .trace = runtime_trace,
};
""",
                encoding="utf-8",
            )
            rust_tests.write_text("fn covers_trace() {}\n", encoding="utf-8")
            zephyr_tests.write_text(
                "ZTEST(squidscript_protocol, test_trace_boundary)\n",
                encoding="utf-8",
            )
            manifest.write_text(
                json.dumps(
                    {
                        "format": "squidscript-squidvm-ffi-abi-v1",
                        "exports": [
                            {
                                "name": "sqvm_present",
                                "family": "vm",
                                "direction": "rust_to_c",
                                "prototype": "void sqvm_present(void);",
                            },
                            {
                                "name": "sqvm_missing",
                                "family": "vm",
                                "direction": "rust_to_c",
                                "prototype": "void sqvm_missing(void);",
                            },
                        ],
                        "callbacks": [
                            {
                                "field": "trace",
                                "typedef": "SqvmTraceCallback",
                                "family": "core",
                                "rust_type": "Option<unsafe extern \"C\" fn(user_data: *mut c_void)>",
                                "missing_policy": "noop",
                            },
                            {
                                "field": "missing_callback",
                                "typedef": "SqvmMissingCallback",
                                "family": "core",
                                "rust_type": "Option<unsafe extern \"C\" fn(user_data: *mut c_void)>",
                                "missing_policy": "noop",
                            },
                        ],
                        "types": [
                            {
                                "name": "SqvmTraceCallback",
                                "definition": "typedef void (*SqvmTraceCallback)(void *user_data);",
                            },
                            {
                                "name": "SqvmCallbacks",
                                "definition": "typedef struct {\n\tSqvmTraceCallback trace;\n} SqvmCallbacks;",
                            },
                        ],
                        "constants": [],
                        "coverage": [
                            {
                                "family": "Core",
                                "callbacks": ["trace", "missing_callback"],
                                "rust": "fake rust coverage",
                                "zephyr": "fake zephyr coverage",
                                "rust_tests": ["covers_trace", "missing_rust_test"],
                                "zephyr_tests": ["test_trace_boundary", "missing_zephyr_test"],
                            }
                        ],
                    },
                    indent=2,
                ),
                encoding="utf-8",
            )
            doc.write_text(
                """
# Coverage

<!-- BEGIN SQUIDVM_FFI_ABI_MANIFEST -->
stale
<!-- END SQUIDVM_FFI_ABI_MANIFEST -->
""",
                encoding="utf-8",
            )

            result = subprocess.run(
                [
                    sys.executable,
                    str(checker),
                    "--check",
                    "--manifest",
                    str(manifest),
                    "--rust",
                    str(rust),
                    "--header",
                    str(header),
                    "--runtime",
                    str(runtime),
                    "--rust-tests",
                    str(rust_tests),
                    "--zephyr-tests",
                    str(zephyr_tests),
                    "--coverage-doc",
                    str(doc),
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
            )

        self.assertNotEqual(result.returncode, 0)
        output = result.stderr + result.stdout
        self.assertIn("manifest exports missing from Rust", output)
        self.assertIn("sqvm_missing", output)
        self.assertIn("unlisted Rust exports", output)
        self.assertIn("sqvm_unlisted_rust", output)
        self.assertIn("unlisted C header prototypes", output)
        self.assertIn("sqvm_unlisted_header", output)
        self.assertIn("manifest callbacks missing from Rust", output)
        self.assertIn("missing_callback", output)
        self.assertIn("manifest callbacks missing from Zephyr runtime wiring", output)
        self.assertIn("manifest coverage evidence missing", output)
        self.assertIn("missing_rust_test", output)
        self.assertIn("missing_zephyr_test", output)
        self.assertIn("coverage doc generated section is stale", output)

    def test_vm_context_reserve_tracks_current_ffi_size(self):
        runtime_h = self.read("firmware/zephyr/src/vm_runtime.h")
        limits_rs = self.read("compiler/rust/crates/squidvm-core/src/limits.rs")
        ffi_rs = self.read("compiler/rust/crates/squidvm-ffi/src/lib.rs")
        ztest = self.read("firmware/zephyr/tests/protocol/src/main.c")

        self.assertIn("pub const MAX_RUNTIME_RECORD_FIELDS: usize = 26;", limits_rs)
        self.assertNotIn("pub const MAX_RUNTIME_RECORD_FIELDS: usize = 32;", limits_rs)
        self.assertIn("const ZEPHYR_RUNTIME_CONTEXT_BYTES: usize = 7_872;", ffi_rs)
        self.assertNotIn("const ZEPHYR_RUNTIME_CONTEXT_BYTES: usize = 8_704;", ffi_rs)
        self.assertNotIn("const ZEPHYR_RUNTIME_CONTEXT_BYTES: usize = 8_624;", ffi_rs)
        self.assertNotIn("const ZEPHYR_RUNTIME_CONTEXT_BYTES: usize = 10_304;", ffi_rs)
        self.assertNotIn("const ZEPHYR_RUNTIME_CONTEXT_BYTES: usize = 10_496;", ffi_rs)
        self.assertNotIn("const ZEPHYR_RUNTIME_CONTEXT_BYTES: usize = 10_624;", ffi_rs)
        self.assertNotIn("const ZEPHYR_RUNTIME_CONTEXT_BYTES: usize = 10_880;", ffi_rs)
        self.assertIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 7872", runtime_h)
        self.assertIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 7872", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 8704", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 8704", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 8624", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 8624", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 10304", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 10304", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 10496", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 10496", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 10624", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 10624", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 10880", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 10880", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 15040", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 15040", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 11776", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 11776", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 12032", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 12032", ztest)
        self.assertNotIn("#define SQ_VM_RUNTIME_CONTEXT_BYTES 12288", runtime_h)
        self.assertNotIn("SQ_VM_RUNTIME_CONTEXT_BYTES <= 12288", ztest)

    def test_app_id_capacity_is_bounded_across_firmware_protocol_and_ffi(self):
        app_store_h = self.read("firmware/zephyr/src/app_store.h")
        ffi_h = self.read("firmware/zephyr/src/squidvm_ffi.h")
        ffi_rs = self.read("compiler/rust/crates/squidvm-ffi/src/lib.rs")
        protocol_rs = self.read("compiler/rust/crates/squid-device-protocol/src/lib.rs")

        self.assertIn("#define SQ_APP_STORE_APP_ID_MAX 40", app_store_h)
        self.assertIn("uint8_t app_id[40];", ffi_h)
        self.assertIn("const SQDP_APP_ID_CAP: usize = 40;", ffi_rs)
        self.assertIn("pub const MAX_APP_ID_LEN: usize = 40;", protocol_rs)
        self.assertNotIn("#define SQ_APP_STORE_APP_ID_MAX 48", app_store_h)
        self.assertNotIn("uint8_t app_id[48];", ffi_h)
        self.assertNotIn("const SQDP_APP_ID_CAP: usize = 48;", ffi_rs)
        self.assertNotIn("pub const MAX_APP_ID_LEN: usize = 48;", protocol_rs)

    def test_app_list_entry_uses_32_bit_sqbc_length_across_firmware_and_ffi(self):
        app_store_h = self.read("firmware/zephyr/src/app_store.h")
        app_store_c = self.read("firmware/zephyr/src/app_store.c")
        ffi_h = self.read("firmware/zephyr/src/squidvm_ffi.h")
        ffi_rs = self.read("compiler/rust/crates/squidvm-ffi/src/lib.rs")
        protocol_c = self.read("firmware/zephyr/src/device_protocol.c")
        build_doc = self.read("docs/firmware_build_architecture.md")

        self.assertIn("uint32_t sqbc_len;", app_store_h)
        self.assertIn("uint32_t sqbc_len;", ffi_h)
        self.assertIn("pub sqbc_len: u32,", ffi_rs)
        self.assertIn("#if defined(CONFIG_SOC_ESP32C3)", app_store_c)
        self.assertIn("BUILD_ASSERT(sizeof(size_t) == sizeof(uint32_t));", app_store_c)
        self.assertIn("#endif", app_store_c)
        self.assertIn("BUILD_ASSERT(sizeof(struct sq_app_registry_entry) == sizeof(SqdpAppListEntry));", protocol_c)
        self.assertIn("ESP32-C3 firmware target uses a 32-bit, 4-byte `size_t`", build_doc)
        self.assertNotIn("size_t sqbc_len;", app_store_h)
        self.assertNotIn("size_t sqbc_len;", ffi_h)
        self.assertNotIn("pub sqbc_len: usize,", ffi_rs)

    def test_device_binding_planning_stays_in_rust_ffi(self):
        ffi_h = self.read("firmware/zephyr/src/squidvm_ffi.h")
        runtime = self.read("firmware/zephyr/src/vm_runtime_device_config.c")
        ffi_rs = self.read("compiler/rust/crates/squidvm-ffi/src/lib.rs")
        ztest = self.read("firmware/zephyr/tests/protocol/src/main.c")

        self.assertIn("SqdcDeviceBindingPlan", ffi_h)
        self.assertIn("sqdc_plan_device_binding", ffi_h)
        self.assertIn("sqdc_plan_device_binding", runtime)
        self.assertIn("plan_device_binding_bytes", ffi_rs)
        self.assertIn("test_sqdc_ffi_plans_device_binding_resources", ztest)
        self.assertNotIn("inline_config;", ffi_h)
        self.assertNotIn("sq_vm_runtime_apply_inline_gpio_indicator_binding", runtime)
        ffi_wrapper = ffi_rs[
            ffi_rs.index("pub unsafe extern \"C\" fn sqdc_plan_device_binding")
            : ffi_rs.index("#[repr(C)]\npub struct SqvmContext")
        ]
        planner = ffi_rs[
            ffi_rs.index("fn plan_device_binding_bytes")
            : ffi_rs.index("fn valid_device_binding_name")
        ]
        self.assertNotIn("let mut plan = SqdcDeviceBindingPlan::default();", ffi_wrapper)
        self.assertNotIn("let mut alias = [0u8; SQVM_DEVICE_BINDING_NAME_CAP];", planner)

    def test_vm_dispatch_uses_static_callbacks_and_separate_user_data(self):
        runtime = self.read("firmware/zephyr/src/vm_runtime.c")
        ffi_h = self.read("firmware/zephyr/src/squidvm_ffi.h")
        ffi_rs = self.read("compiler/rust/crates/squidvm-ffi/src/lib.rs")
        start = runtime.index("int sq_vm_runtime_dispatch")
        end = runtime.index("int sq_vm_runtime_start")
        body = runtime[start:end]

        self.assertIn("static const SqvmCallbacks runtime_callbacks", runtime)
        self.assertNotIn("SqvmCallbacks callbacks;", body)
        self.assertNotIn("callbacks = (SqvmCallbacks)", body)
        self.assertIn("sqvm_context_init_in_place(runtime->context_words, runtime,", body)
        self.assertIn("&runtime_callbacks", body)
        self.assertIn(
            "SqvmStatus sqvm_dispatch_start_resumable(\n\tvoid *context,\n\tvoid *user_data,\n\tconst SqvmCallbacks *callbacks,",
            ffi_h,
        )
        self.assertIn("callbacks: *const SqvmCallbacks", ffi_rs)
        self.assertIn("user_data: *mut c_void", ffi_rs)
        self.assertIn("FfiHost::new(user_data, callbacks, true)", ffi_rs)

    def test_zephyr_vm_runtime_wires_system_resource_callbacks(self):
        ffi_h = self.read("firmware/zephyr/src/squidvm_ffi.h")
        runtime_c = self.read("firmware/zephyr/src/vm_runtime_system.c")
        runtime_callbacks = self.read("firmware/zephyr/src/generated_runtime_callbacks.inc")
        runtime_h = self.read("firmware/zephyr/src/vm_runtime.h")

        self.assertIn("SqvmSystemMemoryTextCallback system_memory_text", ffi_h)
        self.assertIn("SqvmSystemStorageTextCallback system_storage_text", ffi_h)
        self.assertIn("runtime_system_memory_text", runtime_c)
        self.assertIn("runtime_system_storage_text", runtime_c)
        self.assertIn(".system_memory_text = runtime_system_memory_text", runtime_callbacks)
        self.assertIn(".system_storage_text = runtime_system_storage_text", runtime_callbacks)
        self.assertIn("sq_vm_runtime_set_store_mount_point", runtime_h)

    def test_zephyr_header_exposes_bounded_rust_device_config_core(self):
        ffi_h = self.read("firmware/zephyr/src/squidvm_ffi.h")
        ffi_rs = self.read("compiler/rust/crates/squidvm-ffi/src/lib.rs")
        ztest = self.read("firmware/zephyr/tests/protocol/src/main.c")

        self.assertIn("#define SQDC_CONFIG_MAX_RECORDS 5", ffi_h)
        self.assertNotIn("#define SQDC_CONFIG_MAX_RECORDS 6", ffi_h)
        self.assertNotIn("#define SQDC_CONFIG_MAX_RECORDS 8", ffi_h)
        self.assertIn("pub const SQDC_CONFIG_MAX_RECORDS: usize = 5;", ffi_rs)
        self.assertNotIn("pub const SQDC_CONFIG_MAX_RECORDS: usize = 6;", ffi_rs)
        self.assertIn("#define SQDC_CONFIG_KEY_CAP 32", ffi_h)
        self.assertIn("#define SQDC_CONFIG_STRING_CAP 48", ffi_h)
        self.assertNotIn("#define SQDC_CONFIG_STRING_CAP 64", ffi_h)
        self.assertIn("typedef struct {\n\tSqdcRecord records[SQDC_CONFIG_MAX_RECORDS];", ffi_h)
        self.assertIn("sqdc_parse_sqdevice", ffi_h)
        self.assertIn("sqdc_config_set_string", ffi_h)
        self.assertIn("sqdc_encode_sqdc", ffi_h)
        self.assertIn("sqdc_decode_sqdc", ffi_h)
        self.assertIn("test_sqdc_ffi_parses_and_encodes_device_config", ztest)
