[package]
name = "squidvm-ffi"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
crate-type = ["staticlib", "rlib"]

[features]
default = []
zephyr = []

[dependencies]
squid-device-protocol = { path = "../squid-device-protocol", default-features = false }
squidvm-core = { path = "../squidvm-core" }
binbook-core = { path = "../../../../../binbook/crates/binbook-core" }
binbook-decompress = { path = "../../../../../binbook/crates/binbook-decompress" }

[dev-dependencies]
squid-device-protocol = { path = "../squid-device-protocol", features = ["alloc"] }
squidc-core = { path = "../squidc-core" }
crc32fast = "1"
