#!/usr/bin/env python3
"""Generate firmware/zephyr/src/runtime_limits.h from a runtime-limits JSON profile.

Target-generated Kconfig is the build-time tuning source for SquidScript
Zephyr firmware runtime resource caps. This generated header bridges from
CONFIG_* values to the SQ_* C macros used by firmware, with JSON profile
values as standalone/native-test fallbacks.

Usage:
  scripts/generate-runtime-limits-header.py [<json>] [<out_h>]

Defaults:
  json = targets/runtime-limits/esp32c3-zephyr.json
  out_h = firmware/zephyr/src/runtime_limits.h
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_JSON = REPO_ROOT / "targets" / "runtime-limits" / "esp32c3-zephyr.json"
DEFAULT_OUT = REPO_ROOT / "firmware" / "zephyr" / "src" / "runtime_limits.h"

# Section names map to the SQ_ macro prefix. The order matches the JSON
# file's top-level keys but is also enforced here so a reorder does not
# silently change macro names.
SECTION_PREFIX = {
    "vm_runtime": "SQ_VM_RUNTIME",
    "app_store": "SQ_APP_STORE",
    "device_protocol": "SQ_DEVICE",
    "serial_transport": "SQ_SERIAL",
    "ffi": "SQVM",
}

# Per-section key overrides for macro naming consistency with the existing
# C headers. The default rule is SECTION_PREFIX + "_" + key.upper(); these
# overrides match what the C source already uses.
KEY_OVERRIDES = {
    ("vm_runtime", "wifi_ssid_len"): "SQ_VM_RUNTIME_WIFI_SSID_LEN",
    ("vm_runtime", "wifi_bssid_len"): "SQ_VM_RUNTIME_WIFI_BSSID_LEN",
    ("vm_runtime", "wifi_auth_len"): "SQ_VM_RUNTIME_WIFI_AUTH_LEN",
    ("vm_runtime", "wifi_ipv4_len"): "SQ_VM_RUNTIME_WIFI_IPV4_LEN",
    ("vm_runtime", "wifi_profile_name_bytes"): "SQ_VM_RUNTIME_WIFI_PROFILE_NAME_BYTES",
    ("vm_runtime", "wifi_profile_ssid_bytes"): "SQ_VM_RUNTIME_WIFI_PROFILE_SSID_BYTES",
    ("vm_runtime", "wifi_profile_password_bytes"): "SQ_VM_RUNTIME_WIFI_PROFILE_PASSWORD_BYTES",
    ("vm_runtime", "work_stack_size"): "SQ_VM_RUNTIME_WORK_STACK_SIZE",
    ("device_protocol", "response_bytes"): "SQ_DEVICE_RESPONSE_BYTES",
    ("device_protocol", "staging_path_bytes"): "SQ_DEVICE_STAGING_PATH_BYTES",
    ("device_protocol", "resource_path_bytes"): "SQ_DEVICE_RESOURCE_PATH_BYTES",
    ("device_protocol", "install_max_bytes"): "SQ_DEVICE_INSTALL_MAX_BYTES",
    ("serial_transport", "max_frame_len"): "SQ_SERIAL_MAX_FRAME_LEN",
    ("ffi", "storage_transfer_capacity"): "SQVM_STORAGE_TRANSFER_CAPACITY",
    ("ffi", "saved_state_capacity"): "SQVM_SAVED_STATE_CAPACITY",
}


def macro_name(section: str, key: str) -> str:
    override = KEY_OVERRIDES.get((section, key))
    if override is not None:
        return override
    return f"{SECTION_PREFIX[section]}_{key.upper()}"


def render(data: dict) -> str:
    lines: list[str] = []
    lines.append("/*")
    lines.append(" * Generated by scripts/generate-runtime-limits-header.py from")
    lines.append(" * a selected runtime-limits JSON profile. Do not edit by hand.")
    lines.append(" */")
    lines.append("#ifndef SQUIDSCRIPT_RUNTIME_LIMITS_H")
    lines.append("#define SQUIDSCRIPT_RUNTIME_LIMITS_H")
    lines.append("")
    for section, prefix in SECTION_PREFIX.items():
        values = data.get(section)
        if not isinstance(values, dict):
            continue
        lines.append(f"/* {section} */")
        for key in sorted(values):
            if key.startswith("_"):
                continue
            value = values[key]
            if not isinstance(value, int):
                raise ValueError(
                    f"{section}.{key} must be an integer (got {type(value).__name__})"
                )
            name = macro_name(section, key)
            config_name = f"CONFIG_{name}"
            lines.append(f"#if defined({config_name})")
            lines.append(f"#define {name} {config_name}")
            lines.append("#else")
            lines.append(f"#define {name} {value}")
            lines.append("#endif")
        lines.append("")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    json_path = Path(argv[1]).resolve() if len(argv) > 1 else DEFAULT_JSON
    out_path = Path(argv[2]).resolve() if len(argv) > 2 else DEFAULT_OUT

    if not json_path.is_file():
        print(f"generate-runtime-limits-header: JSON not found: {json_path}", file=sys.stderr)
        return 2

    with json_path.open(encoding="utf-8") as handle:
        data = json.load(handle)

    rendered = render(data)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {out_path} ({len(rendered)} bytes, {len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
