[package]
name = "embassy-wifi-ap-probe"
version = "0.1.0"
edition = "2024"
publish = false
license = "AGPL-3.0-only"

[workspace]

[dependencies]
edge-dhcp = "0.7.0"
edge-nal = "0.6.0"
edge-nal-embassy = "0.8.1"
embassy-executor = "0.10.0"
embassy-net = { version = "0.8.0", features = ["dhcpv4", "medium-ethernet", "tcp", "udp"] }
embassy-time = "0.5.0"
embedded-io-async = "0.7"
esp-alloc = { version = "0.10", default-features = false, features = ["esp32c3", "compat", "global-allocator"] }
esp-backtrace = { version = "0.19", default-features = false, features = ["esp32c3", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.5", default-features = false, features = ["esp32c3"] }
esp-hal = { version = "1.1.1", default-features = false, features = ["esp32c3", "rt", "log-04", "unstable"] }
esp-println = { version = "0.17", default-features = false, features = ["esp32c3", "jtag-serial", "log-04"] }
esp-radio = { version = "0.18", default-features = false, features = ["esp32c3", "wifi", "esp-alloc", "log-04", "print-logs-from-driver", "unstable"] }
esp-rtos = { version = "0.3", default-features = false, features = ["esp32c3", "esp-radio", "esp-alloc", "embassy", "log-04"] }
log = "0.4.27"
static_cell = "2.1.0"

[profile.release]
debug = true
debug-assertions = true
lto = "fat"
codegen-units = 1
